config/routes.rb
Coffeerate::Application.routes.draw do
  match '/rate' => 'rater#create', :as => 'rate'

  resources :coffee_beans

  resources :suppliers

  devise_for :users

  root :to => 'welcome#index'

end

app/models/coffee_bean.rb
class CoffeeBean < ActiveRecord::Base
  attr_accessible :description, :name, :supplier_id

  belongs_to :supplier

  letsrate_rateable "overall", "flavour", "aroma", "bitterness"

end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
  
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true 
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :name

  has_many :coffee_beans
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  letsrate_rater
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/coffee_beans_controller.rb
class CoffeeBeansController < ApplicationController
  # GET /coffee_beans
  # GET /coffee_beans.json
  before_filter :authenticate_user!
  
  def index
    @coffee_beans = CoffeeBean.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @coffee_beans }
    end
  end

  # GET /coffee_beans/1
  # GET /coffee_beans/1.json
  def show
    @coffee_bean = CoffeeBean.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coffee_bean }
    end
  end

  # GET /coffee_beans/new
  # GET /coffee_beans/new.json
  def new
    @coffee_bean = CoffeeBean.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coffee_bean }
    end
  end

  # GET /coffee_beans/1/edit
  def edit
    @coffee_bean = CoffeeBean.find(params[:id])
  end

  # POST /coffee_beans
  # POST /coffee_beans.json
  def create
    @coffee_bean = CoffeeBean.new(params[:coffee_bean])

    respond_to do |format|
      if @coffee_bean.save
        format.html { redirect_to @coffee_bean, notice: 'Coffee bean was successfully created.' }
        format.json { render json: @coffee_bean, status: :created, location: @coffee_bean }
      else
        format.html { render action: "new" }
        format.json { render json: @coffee_bean.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /coffee_beans/1
  # PUT /coffee_beans/1.json
  def update
    @coffee_bean = CoffeeBean.find(params[:id])

    respond_to do |format|
      if @coffee_bean.update_attributes(params[:coffee_bean])
        format.html { redirect_to @coffee_bean, notice: 'Coffee bean was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coffee_bean.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_beans/1
  # DELETE /coffee_beans/1.json
  def destroy
    @coffee_bean = CoffeeBean.find(params[:id])
    @coffee_bean.destroy

    respond_to do |format|
      format.html { redirect_to coffee_beans_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController 
  
  def create
                                  
    if current_user.present?
      obj = params[:klass].constantize.find(params[:id])
      obj = eval "#{params[:klass]}.find(#{params[:id]})"     
      if params[:dimension].present?
        obj.rate params[:score].to_i, current_user.id, "#{params[:dimension]}"       
      else
        obj.rate params[:score].to_i, current_user.id 
      end
      
      render :json => true 
    else
      render :json => false        
    end
  end                                        
  
  
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  # GET /suppliers
  # GET /suppliers.json

  before_filter :authenticate_user!
  
  def index
    @suppliers = Supplier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suppliers }
    end
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplier }
    end
  end

  # GET /suppliers/new
  # GET /suppliers/new.json
  def new
    @supplier = Supplier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplier }
    end
  end

  # GET /suppliers/1/edit
  def edit
    @supplier = Supplier.find(params[:id])
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(params[:supplier])

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render json: @supplier, status: :created, location: @supplier }
      else
        format.html { render action: "new" }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suppliers/1
  # PUT /suppliers/1.json
  def update
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      if @supplier.update_attributes(params[:supplier])
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_beans_helper.rb
module CoffeeBeansHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coffee_beans/_form.html.haml
= simple_form_for @coffee_bean do |f|
  - if @coffee_bean.errors.any?
    #error_explanation
      %h2= "#{pluralize(@coffee_bean.errors.count, "error")} prohibited this coffee_bean from being saved:"
      %ul
        - @coffee_bean.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name
  = f.association :supplier
  = f.input :description
  = f.button :submit

app/views/coffee_beans/edit.html.haml
%h1 Editing coffee_bean

= render 'form'

= link_to 'Show', @coffee_bean
\|
= link_to 'Back', coffee_beans_path

app/views/coffee_beans/index.html.haml
%h1 Listing coffee_beans

%table
  %tr
    %th Name
    %th Overall Rating
    %th
    %th
    %th

  - @coffee_beans.each do |coffee_bean|
    %tr
      %td= coffee_bean.name
      %td= rating_for coffee_bean, "overall", :read_only => true
      %td= link_to 'Show', coffee_bean
      %td= link_to 'Edit', edit_coffee_bean_path(coffee_bean)
      %td= link_to 'Destroy', coffee_bean, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Coffee bean', new_coffee_bean_path

app/views/coffee_beans/new.html.haml
%h1 New coffee_bean

= render 'form'

= link_to 'Back', coffee_beans_path

app/views/coffee_beans/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @coffee_bean.name
%p
  %b Supplier:
  = @coffee_bean.supplier_id
%p
  %b Description:
  = @coffee_bean.description

%p
  %b Your Ratings

  .rating-group
    .rating
      .name Overall: 
      = rating_for @coffee_bean, "overall"
    .rating
      .name Flavour: 
      = rating_for @coffee_bean, "flavour"
    .rating
      .name Aroma: 
      = rating_for @coffee_bean, "aroma"
    .rating
      .name Bitterness: 
      = rating_for @coffee_bean, "bitterness"

= link_to 'Edit', edit_coffee_bean_path(@coffee_bean)
\|
= link_to 'Back', coffee_beans_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffeerate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/suppliers/_form.html.haml
= simple_form_for @supplier do |f|
  - if @supplier.errors.any?
    #error_explanation
      %h2= "#{pluralize(@supplier.errors.count, "error")} prohibited this supplier from being saved:"
      %ul
        - @supplier.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name
  = f.button :submit

app/views/suppliers/edit.html.haml
%h1 Editing supplier

= render 'form'

= link_to 'Show', @supplier
\|
= link_to 'Back', suppliers_path

app/views/suppliers/index.html.haml
%h1 Listing suppliers

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @suppliers.each do |supplier|
    %tr
      %td= supplier.name
      %td= link_to 'Show', supplier
      %td= link_to 'Edit', edit_supplier_path(supplier)
      %td= link_to 'Destroy', supplier, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Supplier', new_supplier_path

app/views/suppliers/new.html.haml
%h1 New supplier

= render 'form'

= link_to 'Back', suppliers_path

app/views/suppliers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @supplier.name

= link_to 'Edit', edit_supplier_path(@supplier)
\|
= link_to 'Back', suppliers_path

app/views/welcome/index.html.haml
%h1 Welcome

= link_to "View and Rate Coffee's", coffee_beans_path